// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArSDsicCEODBVLbRUokEYskENmtRakGMc',
    appId: '1:269920561238:web:43984c25720756eb9ff3f7',
    messagingSenderId: '269920561238',
    projectId: 'rpl-notepad',
    authDomain: 'rpl-notepad.firebaseapp.com',
    storageBucket: 'rpl-notepad.firebasestorage.app',
    measurementId: 'G-SETVKCXPP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGKqSHfiyOvRPvxec-Eqfct24IRqCGblo',
    appId: '1:269920561238:android:c546f0357040099f9ff3f7',
    messagingSenderId: '269920561238',
    projectId: 'rpl-notepad',
    storageBucket: 'rpl-notepad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH6P68sCQ-bpGZoLEqOs-vhGuzodqhwqA',
    appId: '1:269920561238:ios:bc741ddf306abdb39ff3f7',
    messagingSenderId: '269920561238',
    projectId: 'rpl-notepad',
    storageBucket: 'rpl-notepad.firebasestorage.app',
    iosBundleId: 'com.example.rplNotepadFe',
  );

}