# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Bump version, build & upload APK to Firebase App Distribution"
  lane :deploy_firebase do |options|
    version_name = options[:version_name] || "1.0.0"

    gradle_file = "app/build.gradle"
    sh("sed -i '' 's/versionName \".*\"/versionName \"#{version_name}\"/' #{gradle_file}")

    increment_version_code(
      gradle_file: gradle_file
    )

    # Build APK 
    sh("flutter build apk --release")

    # Path
    release_notes_path = "./fastlane/release_notes/#{version_name}.txt"
    unless File.exist?(release_notes_path)
      UI.user_error!("Release notes untuk versi #{version_name} tidak ditemukan di #{release_notes_path}")
    end

    # Upload 
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      groups: "sombar",
      release_notes_file: release_notes_path
    )
  end
end
